// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCESP7PYnZHuqa3T4yZAjh6w9nESnhHUT4',
    appId: '1:567705907889:web:d96639388cae4cbfdba890',
    messagingSenderId: '567705907889',
    projectId: 'moncarburant-89937',
    authDomain: 'moncarburant-89937.firebaseapp.com',
    storageBucket: 'moncarburant-89937.firebasestorage.app',
    measurementId: 'G-1VENL63T1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSzyhCtsoeZb1hr7QZdJT3RYjrG6z3jQo',
    appId: '1:567705907889:android:da6072c85a8ec935dba890',
    messagingSenderId: '567705907889',
    projectId: 'moncarburant-89937',
    storageBucket: 'moncarburant-89937.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy7Lba1xBZz1lEOD7WcZp-4Ymuacf1Kq8',
    appId: '1:567705907889:ios:8f844a50188a7c0edba890',
    messagingSenderId: '567705907889',
    projectId: 'moncarburant-89937',
    storageBucket: 'moncarburant-89937.firebasestorage.app',
    iosBundleId: 'com.moncarburant.monCarburantApp',
  );
}
